### ISSUE TITLE
Problem about 'activities'

### ISSUE THREAD

**Issue by suyeonHeo** [ErikBjare/N-Back#2]
Hello,
Really nice to update the code.
I also have a same problem with the lower researcher.
Can you please tell me how to fix this problem?
Thanks,

Here is my problem:

C:\Users\admin\AppData\Local\Programs\Python\Python35\python.exe C:/Users/admin/Desktop/N-Back-master/N-Back-master/main.py
Traceback (most recent call last):
  File "C:/Users/admin/Desktop/N-Back-master/N-Back-master/main.py", line 19, in <module>
    from nBack import NBack
  File "C:\Users\admin\Desktop\N-Back-master\N-Back-master\nBack.py", line 15, in <module>
    import UI
  File "C:\Users\admin\Desktop\N-Back-master\N-Back-master\UI\__init__.py", line 10, in <module>
    import activities
ImportError: No module named 'activities'

**Comment by ErikBjare** [comment]
Run the program with `python .`, not `python main.py`.

**Comment by ErikBjare** [comment]
My bad, `python main.py` is correct. I fixed the issue in a new commit.
